FROM python:3.10-slim

WORKDIR /app

# Install MLflow and its dependencies
RUN pip install --no-cache-dir mlflow==2.14.1 boto3 psycopg2-binary

# Expose the default MLflow port
EXPOSE 5000

# Run MLflow tracking server
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "/mlruns"]
