FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Upgrade pip and wheel
RUN pip install --no-cache-dir --upgrade pip setuptools wheel

# Install MLflow & dependencies
RUN pip install --no-cache-dir \
    mlflow==2.15.1 \
    kafka-python==2.0.2 \
    pandas==2.1.4 \
    evidently==0.4.9 \
    "numpy<2" \
    tqdm \
    requests \
    psutil
