name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint
        run: pip install ruff && ruff .

      - name: Run API test
        run: |
          python - << 'EOF'
          import requests
          r = requests.post(
              "http://localhost:8000/predict",
              json={"rows": [{"midprice": 100, "spread": 0.5, "trade_intensity": 1.2, "volatility_30s": 0.00005}]}
          )
          assert r.status_code == 200
          EOF
