name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install base dependencies (lint + tests)
        run: |
          pip install -r requirements.txt
          pip install pytest ruff

      - name: Lint
        run: ruff check .

      - name: Start model-server stack (thin slice)
        run: |
          docker compose up -d model-server mlflow kafka zookeeper
          echo "Waiting for API health..."
          python - << 'EOF'
          import time, requests

          url = "http://localhost:8000/health"
          for i in range(30):
              try:
                  r = requests.get(url, timeout=1)
                  if r.status_code == 200:
                      print("Healthcheck OK")
                      break
              except Exception:
                  time.sleep(1)
          else:
              raise SystemExit("Healthcheck failed after 30s")
          EOF

      - name: Run integration test
        run: pytest -q --disable-warnings --maxfail=1 tests/test_predict.py
